const config=require('../config'); const repository=require('../repositories'); const telemetry=require('./telemetryService'); const transportService=require('./transportService'); const optimizationService=require('./routeOptimizationService'); const {generate}=require('../../simulator/sensor-generator'); const {SCENARIOS}=require('../../simulator/scenarios');
const initialTelemetry=Object.freeze({temperatura:4,umidade:58,impacto:.1,bateria:100,sinal:100,aceleracao:.25,aceleracao_x:.25,aceleracao_y:0,aceleracao_z:1});let timer=null;let state={running:false,transporteId:1,tick:0,scenarioTick:0,scenario:'normal',progress:0,battery:100,routeId:null,digitalSignal:{alertOutput:false,ledOn:false,buzzerOn:false}};
async function tick(){if(!state.running)return;state.scenarioTick++;try{const payload=generate(state);const result=await telemetry.receive(payload);state.digitalSignal=result.digitalSignal;if(state.scenario==='sinal'&&state.scenarioTick===7)await repository.createEvento({transporteId:state.transporteId,tipoEvento:'COMUNICACAO_RESTABELECIDA',descricao:'Comunicação simulada restabelecida.',latitude:payload.latitude,longitude:payload.longitude});if(state.progress>=1){await stop();await transportService.finish(state.transporteId)}}catch(error){console.error('Falha no simulador:',error.message)}}
async function start(transporteId=1,rotaId){state.transporteId=Number(transporteId);if(!await repository.getTransporte(state.transporteId))throw Object.assign(new Error('Transporte não encontrado.'),{status:404});if(!rotaId)throw Object.assign(new Error('Calcule a rota ótima antes de iniciar o transporte.'),{status:409});state.routeId=String(rotaId);state.running=true;if(!timer)timer=setInterval(tick,config.simulatorIntervalMs);await transportService.start(state.transporteId);return status()}
async function stop(){state.running=false;if(timer){clearInterval(timer);timer=null}return status()}
async function reset(transporteId=state.transporteId){await stop();state={running:false,transporteId:Number(transporteId),tick:0,scenarioTick:0,scenario:'normal',progress:0,battery:100,routeId:null,digitalSignal:{alertOutput:false,ledOn:false,buzzerOn:false}};optimizationService.refreshConditions(state.transporteId);await repository.updateTransporte(state.transporteId,{status:'PREPARADO',inicio_transporte:null,fim_transporte:null});return status()}
async function scenario(name,transporteId){if(!SCENARIOS[name])throw Object.assign(new Error('Cenário inválido.'),{status:400});if(transporteId!==undefined){const id=Number(transporteId);if(!await repository.getTransporte(id))throw Object.assign(new Error('Transporte não encontrado.'),{status:404});state.transporteId=id}state.scenario=name;state.scenarioTick=0;if(name==='normal'){state.battery=100;await repository.createEvento({transporteId:state.transporteId,tipoEvento:'CONDICOES_NORMALIZADAS',descricao:'Cenário normal reativado.'})}if(name==='bateria')state.battery=40;if(name==='atraso')await repository.createEvento({transporteId:state.transporteId,tipoEvento:'ATRASO_SIMULADO',descricao:'Velocidade reduzida para demonstração de atraso.'});if(name==='sinal')await repository.createEvento({transporteId:state.transporteId,tipoEvento:'COMUNICACAO_INTERROMPIDA',descricao:'Perda temporária de sinal simulada.'});if(name==='concluir'){state.progress=1;await tick();await stop();await transportService.finish(state.transporteId)}else if(state.running)await tick();return status()}
function status(){return{...state,initialTelemetry,availableScenarios:Object.entries(SCENARIOS).map(([id,v])=>({id,label:v.label}))}}
module.exports={start,stop,reset,scenario,status,tick};
