const repository=require('../repositories');
const { getRoute }=require('../../simulator/route-generator');
const { routeDistance }=require('../utils/geo');

async function start(id){const transport=await repository.getTransporte(id);if(!transport)throw Object.assign(new Error('Transporte não encontrado.'),{status:404});const started=await repository.updateTransporte(id,{status:'EM_ANDAMENTO',inicio_transporte:new Date(),fim_transporte:null});await repository.createEvento({transporteId:id,tipoEvento:'TRANSPORTE_INICIADO',descricao:'Transporte demonstrativo iniciado.',latitude:transport.latitude_origem,longitude:transport.longitude_origem});return started}
async function finish(id){const transport=await repository.getTransporte(id);if(!transport)throw Object.assign(new Error('Transporte não encontrado.'),{status:404});const finished=await repository.updateTransporte(id,{status:'CONCLUIDO',fim_transporte:new Date()});await repository.createEvento({transporteId:id,tipoEvento:'TRANSPORTE_CONCLUIDO',descricao:'Transporte demonstrativo concluído. Condições monitoradas e ocorrências registradas.',latitude:transport.latitude_destino,longitude:transport.longitude_destino});return finished}
async function tracking(id){const transport=await repository.getTransporte(id),readings=(await repository.getLeituras(id,500)).reverse();if(!transport)throw Object.assign(new Error('Transporte não encontrado.'),{status:404});const optimization=await repository.getLatestOptimization(id),routeId=optimization?.selectedRouteId||'ROTA_A',route=getRoute(routeId),points=route.points,last=readings.at(-1);let progress=0;if(last){let nearest=0,min=Infinity;points.forEach((p,i)=>{const d=(p.latitude-last.latitude)**2+(p.longitude-last.longitude)**2;if(d<min){min=d;nearest=i}});progress=nearest/(points.length-1)*100}const totalKm=route.distancia;return{origin:{latitude:transport.latitude_origem,longitude:transport.longitude_origem,name:transport.hospital_origem},destination:{latitude:transport.latitude_destino,longitude:transport.longitude_destino,name:transport.hospital_destino},current:last?{latitude:last.latitude,longitude:last.longitude}:null,route:points,routeId,routeName:route.nome,path:readings.map(r=>({latitude:r.latitude,longitude:r.longitude})),progress,totalKm,traveledKm:totalKm*progress/100,remainingKm:totalKm*(1-progress/100)}}
async function summary(id){const transport=await repository.getTransporte(id);const data=await repository.summary(id);const alerts=await repository.getAlertas(id);const start=transport?.inicio_transporte?new Date(transport.inicio_transporte):null;const end=transport?.fim_transporte?new Date(transport.fim_transporte):new Date();return{transport,...data,numero_alertas:alerts.length,duracao_minutos:start?Math.max(0,Math.round((end-start)/60000)):0,status_final:transport?.status}}
module.exports={start,finish,tracking,summary};
